import { Button, Flex, useColorMode } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "../components/Container";
import Editor from "@monaco-editor/react";
import { useRef, useState } from "react";
import { MarkdownProcessor } from "../components/MarkdownProcessor";
import { EditorContainer } from "../components/EditorContainer";

const Home: NextPage = () => {
  const [editorValue, setEditorValue] = useState<string>("");
  const { colorMode, toggleColorMode } = useColorMode();
  const editorRef = useRef(null);

  function handleEditorDidMount(editor: any, monaco: any) {
    editorRef.current = editor;

    if (editorRef.current) {
      // @ts-ignore
      setEditorValue(editorRef?.current.getValue());
    }
  }

  return (
    <Container>
      <Head>
        <title>Hello World</title>
        <meta
          name="description"
          content="Generated by Futhememe boilerplate generator"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EditorContainer
        value={editorValue}
        onChange={(text) => setEditorValue(text ?? "")}
        onMount={handleEditorDidMount}
      />
      <MarkdownProcessor>{editorValue}</MarkdownProcessor>
    </Container>
  );
};

export default Home;
